### ISSUE TITLE
Any interest in light transmitted by building windows?

### ISSUE THREAD

**Issue by RebeccaPowles** [luox-app/luox#63]
Hi,
I came across your project via a LinkedIn daylighting page.  I confess I don't know a great deal about the biological side of your area of research, however I was wondering if there is any interest in your field in the spectral qualities of light transmitted by building windows? 

I used to work at Lawrence Berkeley National Lab and helped to develop the optical calculation code behind the software tool 'Optics' which calculates the (spectral) optical properties of various combinations of window glass from a large international database of glazing product properties.  This software is very old now but is still in wide use and the database is continually updated.  LBNL are working on a new generation of software which will eventually replace the functionality of Optics.  One key part of this is moving the database of glazing product optical properties online and releasing an open source calculation engine that can be used to calculate the optical (and thermal) properties of combinations of products.  The main application of this software is building energy modelling, but the underlying data is also used for daylighting modelling.

I am an independent consultant these days, not associated with LBNL, but I still have an active interest in this area.  I think it would be pretty straightforward to use Optics (or the development version of the newer generation of tools) and a few spreadsheet calculations to generate input spectra for luox.  The calculation would require an input solar spectrum and Optics can supply the spectral transmittance of the glazing at normal incidence.  If there's any interest I would be very happy to contribute a tutorial on how to use Optics to support the calculation of input spectra.  

best regards,
Rebecca Powles

**Comment by spitschan** [comment]
Hi @RebeccaPowles, many thanks for the message. I would be very keen to have a conversation with you about this. Would you be able to drop me a line via email (manuel.spitschan@psy.ox.ac.uk) to find some time to discuss?
