### ISSUE TITLE
Citation File Format - CITATION.cff

### ISSUE THREAD

**Issue by floehopper** [luox-app/luox#64]
GitHub recently announced that they now [have support for](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-citation-files) the human- and machine-readable [Citation File Format](https://citation-file-format.github.io/). I thought you might be interested in creating a `CITATION.cff` file for the repo.

**Comment by floehopper** [comment]
@spitschan I've done some digging into why your `CITATION.cff` file isn't being parsed successfully, but can't work out what's wrong with it. I've opened [this issue](https://github.com/citation-file-format/ruby-cff/issues/65) on the repo for the Ruby gem which GitHub use to do the parsing. Hopefully someone will get back to me with some advice / answers.

**Comment by spitschan** [comment]
Thanks, much appreciated.
________________________________

**Comment by spitschan** [comment]
Fixed for now by adding the version info into the `CITATION.cff` file.
