### ISSUE TITLE
There are 3 wrong values in the CIE 026 dataset

### ISSUE THREAD

**Issue by NilesDavis** [luox-app/luox#96]
Hi!
First at all: thank you for all the work you did! It is great to finally have some persons publishing light computations open source. This is what I was longing for since 2008, but I did not find any acceptance for it.
I know it is a little nerdy, but I compared my implementation with yours and found 3 values in your dataset differing from those, given in the standard CIE S 026:2018. That are 3 values in the L-cone action spectrum at 661, 662 and 663nm each differing +1E-7
Can you confirm this?
Hopefully I can contribute more. Still digging in the code ;)

**Comment by spitschan** [comment]
Thank you for flagging this. There is a discrepancy in the published tables in CIE S 026:2018 and the spectral sensitivities given in the [toolbox](https://bit.ly/2T9QLTL).

CIE S 026:2018:

<img width="495" alt="CIES026.png" src="https://user-images.githubusercontent.com/3341551/182909233-be1ffd47-8321-4004-8aa4-90e9d923807d.png">

Toolbox (see Sheet "Action spectra" in the [spreadsheet](https://bit.ly/2T9QLTL)):

<img width="790" alt="CIES026Toolbox.png" src="https://user-images.githubusercontent.com/3341551/182909265-e883bbfb-4c3e-4227-846f-658eedaaa4c8.png">

In the implementation, we elected to use the version ini the CIE Toolbox.

**Comment by NilesDavis** [comment]
Wow, I didn't check that! Of course this is just of minor impact but do you see a possibility to clarify this, which version is correct? I just saw that you were also involved in the toolbox work, so perhaps this is easier for you than for me? I just know Peter to get in touch with.

**Comment by spitschan** [comment]
I would expect this arises from a truncation / rounding convention.

If you want to get to the bottom of this, you could email [Luc Schlangen](https://research.tue.nl/en/persons/luc-jm-schlangen) or [Luke Price](https://researchportal.ukhsa.gov.uk/en/persons/luke-price).

CIE has validated the results, you can read the report here: https://raw.githubusercontent.com/luox-app/luox/master/docs/CIE_Software_Check_of_luox_app.pdf.
