### ISSUE TITLE
Inconsistency in Standards used for Standard illuminants

### ISSUE THREAD

**Issue by NilesDavis** [luox-app/luox#97]
I found that in the dataset for standard illuminants (reference_spectra.json) that 2 datasets are taken from other sources. So C, D50, D55 and D75 are taken from the CIE 015:2018 as they are in 5nm resolution as given in the standard. Standard illuminants A and D65 are in 1nm and exactly match the dataset from the ISO/CIE 11664-2:2020. What is the reason for this? Shouldn't the 5nm CIE15 data be the reference for all standard illuminants?

**Comment by NilesDavis** [comment]
Okay this is the way you went. So to be consistent I would recommend to use the 1nm dataset from ISO/CIE 11664-2:2020 for D50 as well. Thanks for the quick exchange!

**Comment by spitschan** [comment]
At the time of writing, this document was not available unfortunately. Could you potentially create a pull request with this change? Thanks.

**Comment by spitschan** [comment]
Thank you, much appreciated @NilesDavis.
